### PR TITLE
Games: Star Ruler 2

### PR DESCRIPTION
**Pull request by murlock**
Original source code is now available.

### CODE REVIEW

**Comment by cxong** [comment]
Thanks; there is a schema change about to be merged soon, you may have to edit this PR after that one goes through
#587

**Comment by wonea** [comment]
Can this be merged now?

**Comment by tzizi** [comment]
Sure, I can rebase #587 after

**Comment by tzizi** [comment]
Shouldn't this be listed as a `port`, once the extra types are added?

**Pull request merged**
