### PR TITLE
Add OpenSC2K

### PR DESCRIPTION
**Pull request by rage8885**
Re-added OpenSC2K with updated information

### CODE REVIEW

**Comment by cxong** [comment]
I'm reluctant to let this through. This is the project that got DMCA'd by EA for having original Simcity assets included. It's not blocked now, but the history is still there - https://github.com/rage8885/OpenSC2K/blob/073ef535872eb46b6682ced832a64be463e864d1/images/tilemap/tilemap_0.png. So either EA doesn't care or they don't know hwo git works?
@rage8885 if you [wipe the offending history](https://stackoverflow.com/q/9683279/2038264) I'd be happy to merge this.

**Comment by rage8885** [comment]
@cxong Done

**Comment by cxong** [comment]
Weird, my link still works, but I guess people won't find it easily now. Perhaps git needs to clean up those unreferenced commits with `git gc --aggressive --prune=all`?

**Comment by rage8885** [comment]
@cxong I did that, but it seems GitHub keeps a reference to the old branch/commit somehow. Might expire eventually, but it's no longer accessible via the repository or commit history.

**Pull request merged**
