### PR TITLE
add OpenDrakan (remake of Drakan: Order of the Flame)

### LINKED ISSUE #563: Add OpenDrakan
OpenDrakan

```yaml
- name: OpenDrakan
  remakes: [Drakan: Order of the Flame]
  clones: []
  repo: https://github.com/Zalasus/opendrakan
  url: 
  feed: 
  development: Active
  status: Unplayable
  multiplayer: []
  lang: [C++]
  framework: []
  license: GPL3
  content: Open
  info: 
  updated: 2018-05-19, 15:04 CEST
  images: 
  video:
    youtube:
    vimeo:
```

### PR DESCRIPTION
**Pull request by kparal**
Fixes #563

### CODE REVIEW

**Comment by wonea** [comment]
Resolve the conflicts and I'll happy merege in.

**Comment by kparal** [comment]
Rebased.

**Comment by wonea** [comment]
Thank you very much!

**Comment by kparal** [comment]
Thank you for merging this. How often does the website get refreshed? I was hoping it gets rebuilt automatically after each commit, but it doesn't seem so.

**Comment by wonea** [comment]
It should only be a few moments...

**Comment by kparal** [comment]
The website still hasn't been refreshed, it seems.

**Pull request merged**
