### PR TITLE
add Devilution (reverse engineered Diablo)

### PR DESCRIPTION
**Pull request by fanna**

### CODE REVIEW

**Comment by wonea** [comment]
Thanks

**Comment by wonea** [comment]
If Blizzard do take issue, then yes I agree we remove this item.

**Comment by kparal** [comment]
This breaks build:
```
$ make
cyrax
497 games in total
INFO:pykwalify.core:validation.valid
751 clones in total
ERROR:pykwalify.core:validation.invalid
ERROR:pykwalify.core: --- All found errors ---
ERROR:pykwalify.core:[u"Enum 'Public Domain' does not exist. Path: '/121/license/0'"]


  Devilution
    Enum 'Public Domain' does not exist. Path: '/121/license/0'

  1 errors

make: *** [Makefile:6: build] Error 1
```

**Comment by fanna** [comment]
@kparal Oh I see, it should be `PD` instead of `Public Domain`

**Comment by wonea** [comment]
Sorted.

**Pull request merged**
