### PR TITLE
Added a "demake" / child of Factorio, Mindustry.

### PR DESCRIPTION
**Pull request by mdtrooper**
:beers:

### CODE REVIEW

**Comment by markozajc** [comment]
"demake"

**Comment by Anuken** [comment]
While it is similar in some ways, Mindustry is not a "demake" or "child game" of Factorio. The art, transportation, production, combat, maps, construction, enemies, etc. are completely different between the two games. 

I've only played Factorio a little bit during late Mindustry 4.0 development, but last time I checked, there are quite a few features Mindustry has that Factorio doesn't (RTS mechanics/units, base attack maps, planetary campaign, logic assembly programming, etc). Likewise, Factorio has many mechanics that Mindustry will never have.

**Comment by mdtrooper** [comment]
> While it is similar in some ways, Mindustry is not a "demake" or "child game" of Factorio. The art, transportation, production, combat, maps, construction, enemies, etc. are completely different between the two games.
> 
> I've only played Factorio a little bit during late Mindustry 4.0 development, but last time I checked, there are quite a few features Mindustry has that Factorio doesn't (RTS mechanics/units, base attack maps, planetary campaign, logic assembly programming, etc). Likewise, Factorio has many mechanics that Mindustry will never have.

Sorry @Anuken . Do you see better the `type: similar` in the entry?

Your game is awesome and some years ago I remember the firsts versions (in android phone, without aircraft) and for me (personally) it had a taste to "demake". Demake is not bad word, for me it is a good work because it is take the essence of something (song, film, book, game, boardgame, food recipe...) and do something more tiny or simple or small.

For me, Mindustry, Cataclysm DDA, Pixel Dungeon are the best examples of awesome floss games.

**Comment by Anuken** [comment]
That explains it. The first few versions (3.5 and below) were very small in scope; 5.0+ can no longer be called "simple" or "tiny" anymore. [Mindustry Classic](https://github.com/Anuken/Mindustry-Classic) would be a better fit for this list.

**Pull request merged**
