### PR TITLE
Danger

### PR DESCRIPTION
**Pull request by cxong**
This PR creates a stub integration with Danger CI, as mentioned in #540. The only thing it currently does is list the files changed. You can see an example here: https://github.com/cxong/osgameclones/pull/3

To complete integration, we need to add an environment variable to travis with key/value: `DANGER_GITHUB_API_TOKEN` and `ae25f569fe4418a062e55abddc8c2d971700918a`. This allows @osgameclonesbot to post comments to PRs. I can also provide login details to @osgameclonesbot if anyone else in @opengaming wants to manage this account.

I'll create more PRs in the future to add interesting danger checks like those described in #540.

### CODE REVIEW

**Comment by piranha** [comment]
That is a great idea! What do we need to make it work? Should I just merge it or maybe there is some account needed or what?

**Comment by cxong** [comment]
add an environment variable to travis with key/value: DANGER_GITHUB_API_TOKEN and ae25f569fe4418a062e55abddc8c2d971700918a

image

**Comment by piranha** [comment]
Weird, it still complains that env var does not exist. I'll look into that a little bit later (maybe today in the evening), somewhat busy right now.

P.S. Do you think you need to delete your comment with an API key?

**Comment by piranha** [comment]
Okay, I'm really not sure how to make it work. I've added `DANGER_GITHUB_API_TOKEN` to Travis settings and... it still complains. :\

**Comment by piranha** [comment]
I guess now the PR should be updated against master.

**Comment by cxong** [comment]
not sure if it matters but try adding the env var with the "Display value in build log" enabled
image

**Comment by piranha** [comment]
Ah! Encrypted (hidden) values are not available to pull requests!

But can we have this variable in the open?

**Comment by cxong** [comment]
it should be fine, as the token only allows @osgameclonesbot to comment on PRs in this repo (`public_repo`). See https://danger.systems/js/guides/getting_started.html#tokens-for-oss-projects

**Pull request merged**
